### ISSUE TITLE
How to run unit tests

### ISSUE THREAD

**Issue by mgoblin** [nginx-clojure/nginx-clojure#225] opened 2019-11-07 05:35 UTC
I try to run unit tests as follow
lein clean
lein jar
lein with-profiles +unittest test
The result is exception 
java.lang.NoClassDefFoundError: Lclojure/lang/Keyword; compiling:(nginx/clojure/core.clj:70:1)

How to fix this issue and run unit tests?

**Comment by xfeep** [comment] 2019-11-07 16:32
@mgoblin please try

```
lein with-profiles unittest junit
```

instead of 

```
lein with-profiles unittest test
```

BTW I'll create a yaml file for travis ci because unit test is not enough.

**Comment by mgoblin** [comment] 2019-11-08 06:16
@xfeep Thanx

Now test are executed

Another problem after run 
lein with-profiles unittest test

Output
-----------------
Testcase: testDecodeToString(nginx.clojure.java.StringFacedJavaBodyFilterTest): FAILED
expected:<[?]> but was:<[цмК]>
junit.framework.AssertionFailedError: expected:<[?]> but was:<[цмК]>
        at nginx.clojure.java.StringFacedJavaBodyFilterTest.testDecodeToString(StringFacedJavaBodyFilterTest.java:66)
Test nginx.clojure.java.StringFacedJavaBodyFilterTest FAILED
Testsuite: nginx.clojure.wave.MethodDatabaseUtilTest
Tests run: 4, Failures: 0, Errors: 0, Time elapsed: 0,266 sec
Testsuite: nginx.clojure.wave.TypeInterpreterTest
Tests run: 28, Failures: 0, Errors: 0, Time elapsed: 0,343 sec
JUnit tests failed.
Error encountered performing task 'junit' with profile(s): 'unittest'
JUnit tests failed.
-------------------

Environment: Windows10 , Java 11

**Comment by mgoblin** [comment] 2019-11-08 06:16
Sorry for bold

**Comment by xfeep** [comment] 2019-11-08 13:56
@mgoblin Thank you for letting me know this.  This error is caused by  that on windows the default file encoding is not uft8. It can be fixed by adding an option to lein-junit plugin.  In project.clj

```clojure
             :unittest {
                    :jvm-opts [......
                               "-Dfile.encoding=UTF-8"
                                   .....
                                 ]
```

**Comment by mgoblin** [comment] 2019-11-08 14:49
Thanx
Alternative workaround for Windows cmd run 
set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
and rebuild project

**Closed** 2019-11-08 14:51 UTC
